---

- hosts: all
  become: true
  tasks:

  - name: update repository index
    apt:
      update_cache: yes
    when: ansible_distribution in ["Debian" , "Ubuntu"]

    #to find the possible distribution options 
    #ansible all -m gather_facts --limits <serverIP> | grep ansible_distribution
    # when: ansible_distribution == "Amazon" and ansible_distribution_version == "2"

  - name: install apache2 package
    apt:
      name: apache2
      state: latest
    when: ansible_distribution == "Ubuntu"

  - name: add php support for apache
    apt:
      name: libapache2-mod-php
      state: latest
    when: ansible_distribution == "Ubuntu"

  - name: update repository index
    apt:
      update_cache: yes
    when: ansible_distribution == "Amazon"

  - name: install apache2 package
    apt:
      name: apache2
      state: latest
    when: ansible_distribution == "Amazon"

  - name: add php support for apache
    apt:
      name: libapache2-mod-php
      state: latest
    when: ansible_distribution == "Amazon"
