---

- hosts: all
  become: true
  pre_tasks:

  - name: Install updates on amazon
    tags: always
    package:
      update_only: yes
      update_cache: yes
    when: ansible_distribution == "Amazon"

  - name: Install updates (ubuntu)
    tags: always
    apt: 
      upgrade: dist
      update_cache: yes
    when: ansible_distribution == "Ubuntu"

- hosts: web_servers
  become: true
  tasks:

  - name: install apache2 and php for ubuntu
    tags: apache,apache2,ubuntu
    apt:
      name:
      - apache2
      - libapache2-mod-php
      state: latest
    when: ansible_distribution == "Ubuntu"

  - name: install apache2 and php for amazon
    tags: apache, centos, httpd
    package:
      name:
      - httpd
      - php
      state: latest
    when: ansible_distribution == "Amazon"

  - name: copy default html file for site
    tags: apache, apache2,httpd
    copy:
      src: default_site.html
      dest: /var/www/html/index.html
      owner: root
      group: root
      mode: 0644 

- hosts: db_servers
  become: true
  tasks:

  - name: install mariadb package (Amazon)
    tags: centos,db.mariadb
    package:
      name: mariadb
      state: latest
    when: ansible_distribution == "Amazon"

  - name: install mariadb package (Ubuntu)
    tags: db,mariadb,ubuntu
    package:
      name: mariadb-server
      state: latest
    when: ansible_distribution == "Ubuntu"

- hosts: file_servers
  become: true
  tasks:

  - name: install samba package
    tags: samba
    package:
      name: samba
      state: latest