---


- hosts: all
  become: true
  pre_tasks:

  - name: Install updates on amazon
    package:
      update_only: yes
      update_cache: yes
    when: ansible_distribution == "Amazon"

  - name: Install updates (ubuntu)
    apt: 
      upgrade: dist
      update_cache: yes
    when: ansible_distribution == "Ubuntu"

- hosts: web_servers
  become: true
  tasks:

  - name: install apache2 and php for ubuntu
    apt:
      name:
      - apache2
      - libapache2-mod-php
      state: latest
    when: ansible_distribution == "Ubuntu"

  - name: install apache2 and php for amazon
    package:
      name:
      - httpd
      - php
      state: latest
    when: ansible_distribution == "Amazon"

- hosts: db_servers
  become: true
  tasks:

  - name: install mariadb package (Amazon)
    package:
      name: mariadb
      state: latest
    when: ansible_distribution == "Amazon"

  - name: install mariadb package (Ubuntu)
    package:
      name: mariadb-server
      state: latest
    when: ansible_distribution == "Ubuntu"

- hosts: file_servers
  become: true
  tasks:

  - name: install samba package
    package:
      name: samba
      state: latest