
- name: add ssh key for simone
  tags: always
  authorized_key:
    user: simone
    key: "ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQCHOdJ8/fMsWMyIqH3rSVJlbHWwsw/82NBWwVZEGcHVB48bKxq1tK9koUnZkSyMFWFVGn0nZ23ndkFOI4pmxYciQZ9ctoC2k2Js2MVJWxcDgywoz0OgAfKgEqy7BSXEPdZztjoS7hBNHG9+1z4G2tWexuNQvaGYNMKdPmbJ4bk3MtkFf35V5NJwDpE/yTSNtmrZJpu21AXUSDdNq14aIyJXzTP31uIPoCNZ3kRFKkQJBnOrlxvwOs53eBLySmRUB2r0DuwAC7vKbWkSU1X7L6GpukAhnuJ80b9+vSNKGwvLRM1rdUoqGK0wBtoFKBeKd8JaFfnjyq+RH+N+8whcPc9v udacity"